# VAE config used for VAE training
vae:
  data:
    root: 'data/'
    data_name: "fmnist"
    num_clusters_data: 10
    image_size: 28
    n_channels: 1
    hflip: False

  model:  # VAE specific params. Check the `main/models/vae.py`
    enc_block_config : "32x1,32d4,32t8,8x1,8d4,8t2,2x1"
    enc_channel_config: "32:32,8:64,2:256"
    dec_block_config: "2x1,2u4,2t8,8x2,8u4,8t32,32x1"
    dec_channel_config: "32:32,8:64,2:256"

  training:   # Most of these are same as explained above but for VAE training
    seed: 0
    fp16: False
    batch_size: 128
    epochs: 500
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1
    optimizer: "Adam"
    lr: 0.0001
    restore_path: ""
    results_dir: "vanilla_vae/results/"
    workers: 1
    chkpt_prefix: ""
    alpha: 1.0   # The beta value in beta-vae.
    
  globals:
    seed: 42                    # Random seed for reproducibility