run_name: 'celeba_cnn'

data:
  data_name: 'celeba'
  num_clusters_data: 1
  path: 'datasets/celeba'

training:
  num_epochs: 150
  num_epochs_smalltree: 150
  num_epochs_intermediate_fulltrain: 0
  num_epochs_finetuning: 0
  batch_size: 256
  lr: 0.001
  weight_decay: 0.00001
  decay_lr: 0.1
  decay_stepsize: 100
  decay_kl: 0.01
  kl_start: 0.01
  dropout_router: 0.0
  skip_con_transformation: True
  compute_fid: True
  save_images: True

  inp_shape: 4096 # 12288
  inp_channels: 3 # 3 for RGB
  representation_dim: 4 # size of the 2-dim latent representation -> should be a power of 2, (2, 4, 8, 16 ...)
  latent_channels: [16, 16, 16, 16, 16, 16] # channels of the latent representation
  bottom_up_channels: [64, 64, 64, 64, 64, 64] # channels of the bottom-up representation,
  initial_depth: 1
  activation: 'mse'
  encoder: 'cnn2'
  grow: True
  prune: True
  num_clusters_tree: 10
  intermediate_fulltrain: False
  augment: True
  augmentation_method: 'InfoNCE,instancewise_full' 
  aug_decisions_weight: 100
  compute_ll: False

globals:
  wandb_logging: 'disabled'
  eager_mode: False
  seed: 42
  save_model: True
  config_name: 'celeba'